# Generated by Django 5.1.3 on 2025-01-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, null=True, unique=True, verbose_name='Телефон')),
                ('username', models.CharField(max_length=150, verbose_name='WatsApp Username')),
                ('session', models.CharField(blank=True, max_length=150, null=True, verbose_name='Сессия')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='Последний визит')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='Первый визит')),
                ('comment', models.TextField(blank=True, default='Нет комментариев', null=True, verbose_name='Комментарии о посетителе')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
            },
        ),
        migrations.CreateModel(
            name='ReportEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для рассылки отчетов')),
            ],
            options={
                'verbose_name': 'Email для рассылки',
                'verbose_name_plural': 'Email для рассылки',
            },
        ),
    ]
