# Generated by Django 5.1.3 on 2025-01-19 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0003_productblock_alter_buttonmenu_product_block'),
        ('shop', '0002_alter_cartitem_product_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.productblock'),
        ),
    ]
