# Generated by Django 5.1.3 on 2025-01-20 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('shop', '0003_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_related', to='clients.client'),
        ),
    ]
