# Generated by Django 5.1.3 on 2025-02-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_spot_cartitem_time_spot_order_time_spot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='time_spot',
        ),
        migrations.AlterField(
            model_name='order',
            name='time_spot',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
