# Generated by Django 5.1.3 on 2024-12-02 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_rus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок на русском')),
                ('header_kaz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок на казахском')),
                ('body_rus', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Основной текст на русском')),
                ('body_kaz', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Основной текст на казахском')),
                ('footer_rus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подвал на русском')),
                ('footer_kaz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подвал на казахском')),
                ('list_title_rus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок списка на русском')),
                ('list_title_kaz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок списка на казахском')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название инфоблока для поиска')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_rus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок на русском')),
                ('header_kaz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок на казахском')),
                ('body_rus', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Основной текст на русском')),
                ('body_kaz', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Основной текст на казахском')),
                ('footer_rus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подвал на русском')),
                ('footer_kaz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подвал на казахском')),
                ('list_title_rus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок списка на русском')),
                ('list_title_kaz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок списка на казахском')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название меню для поиска')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ButtonMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_rus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст в кнопке на русском')),
                ('title_kaz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст в кнопке на казахском')),
                ('button_number', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('info_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_button_reverse', to='api_backend.infoblock', verbose_name='При нажатии переход в этот инфоблок')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='api_backend.menublock', verbose_name='Кнопка будет в этом меню')),
                ('menu_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_button_reverse', to='api_backend.menublock', verbose_name='При нажатии переход в это меню')),
            ],
        ),
    ]
