# Generated by Django 5.1.3 on 2024-12-02 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmenu',
            name='info_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_button_reverse', to='api_backend.infoblock', verbose_name='При нажатии переход в этот инфоблок'),
        ),
        migrations.AlterField(
            model_name='buttonmenu',
            name='menu_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_button_reverse', to='api_backend.menublock', verbose_name='При нажатии переход в это меню'),
        ),
    ]
