# Generated by Django 5.1.3 on 2025-01-19 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_rus', models.CharField(blank=True, max_length=59, null=True, verbose_name='Заголовок на русском')),
                ('header_kaz', models.CharField(blank=True, max_length=59, null=True, verbose_name='Заголовок на казахском')),
                ('body_rus', models.TextField(max_length=1020, verbose_name='Основной текст на русском')),
                ('body_kaz', models.TextField(max_length=1020, verbose_name='Основной текст на казахском')),
                ('footer_rus', models.CharField(blank=True, max_length=59, null=True, verbose_name='Подвал на русском')),
                ('footer_kaz', models.CharField(blank=True, max_length=59, null=True, verbose_name='Подвал на казахском')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в тенге')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='buttonmenu',
            name='product_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_button_reverse', to='api_backend.product', verbose_name='При нажатии переход в этот продукт'),
        ),
    ]
