# Generated by Django 5.1.3 on 2024-12-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0002_alter_menublock_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название реплики (ENG)')),
                ('rus', models.TextField(verbose_name='Русская реплика')),
                ('kaz', models.TextField(verbose_name='Казахская реплика')),
                ('reply_type', models.CharField(choices=[('header', 'Заголовок'), ('body', 'Основной текст'), ('footer', 'Подвал'), ('list_title', 'Заголовок списка'), ('section_title', 'Заголовок секции'), ('button', 'Кнопка')], default='button', max_length=100, verbose_name='Тип реплики')),
            ],
            options={
                'verbose_name': 'Остальные реплики',
                'verbose_name_plural': 'Остальные реплики',
            },
        ),
    ]
