# Generated by Django 5.1.3 on 2025-01-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0003_productblock_alter_buttonmenu_product_block'),
        ('shop', '0003_alter_cartitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
