# Generated by Django 5.1.3 on 2024-12-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0004_alter_buttonmenu_info_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmenu',
            name='menu_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_button_reverse', to='api_backend.menublock', verbose_name='При нажатии переход в это меню'),
        ),
    ]
