# Generated by Django 5.1.3 on 2025-01-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0004_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productblock',
            name='product_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
