# Generated by Django 5.1.3 on 2025-01-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0005_alter_productblock_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productblock',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
