# Generated by Django 5.1.3 on 2024-12-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0005_alter_buttonmenu_menu_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoblock',
            name='body_kaz',
            field=models.TextField(max_length=2040, verbose_name='Основной текст на казахском'),
        ),
        migrations.AlterField(
            model_name='infoblock',
            name='body_rus',
            field=models.TextField(max_length=2040, verbose_name='Основной текст на русском'),
        ),
    ]
